version: "3.8"

services:
  backend:
    build:
      context: ./msgr-back
    volumes:
      - ./msgr-back:/app
      - /app/node_modules
    ports:
      - "5050:5050"
    env_file:
      - ./msgr-back/.env
    restart: unless-stopped
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./msgr-front
    volumes:
      - ./msgr-front:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    restart: unless-stopped

  mongodb:
    image: mongo:6
    container_name: msgr-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: msgr-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=
      - ME_CONFIG_MONGODB_ADMINPASSWORD=
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongo_data:
